Cadastro de Atleta
MateuxDotDev/badminton-manager pull request #23
Opened 2023-05-16 01:02 UTC by MateuxLucax

Adicionado possibilidade do técnico logado cadastrar atleta.

2023-05-16 01:04 UTC, ghost commented
![Failed](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/QualityGateBadge/failed.svg?sanitize=true)

- 0.00% Coverage on New Code (is less than 80.00%)

# Analysis Details
## 2 Issues
- ![Bug](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/bug.svg?sanitize=true) 0 Bugs
- ![Vulnerability](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/vulnerability.svg?sanitize=true) 0 Vulnerabilities
- ![Code Smell](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/code_smell.svg?sanitize=true) 2 Code Smells

## Coverage and Duplications
- ![Coverage](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/CoverageChart/0.svg?sanitize=true) 0.00% Coverage (69.30% Estimated after merge)
- ![Duplications](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/Duplications/3.svg?sanitize=true) 0.00% Duplicated Code (0.00% Estimated after merge)

**Project ID:** MateuxDotDev_badminton-manager_AYfNu-knGxuymmoUfIu7

[View in SonarQube](https://sonarqube.mateux.dev/dashboard?id=MateuxDotDev_badminton-manager_AYfNu-knGxuymmoUfIu7&pullRequest=23)

2023-05-17 00:04 UTC, luc527 requested changes
## Erros de funcionalidade

### Upload de imagem png não funciona:

![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/95c51e72-75a2-447b-b5bc-f665e9ce7880)

### Dá erro se o técnico não selecionar uma imagem:

Na verdade são dois erros:
  - O código no back-end não verifica se uma imagem foi enviada ou não (só deveria fazer upload caso tenha imagem na request)
  - O $imageService->removerImagem() deveria verificar se uma imagem foi salva, porque se o método for chamado sem uma imagem dá erro porque acessa a propriedade $this->nomeImagem que não foi inicializada

![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/7c4cb462-94ef-43e5-8951-a8b47fa187f6)

2023-05-17 00:04 UTC, luc527 commented on public/assets/images/profile/6462d594973b7.jpeg
faltou atualizar o .gitignore pra não ir os arquivos

2023-05-17 00:04 UTC, luc527 commented on public/tecnico/atleta/cadastrar/acao.php
> +    try {
precisa desse try-catch se já tem um em volta do cadastroController?

2023-05-17 00:04 UTC, luc527 commented on public/tecnico/atleta/cadastrar/index.php
> +    <h2>Cadastrar atleta</h2>
Usar h1 que nem nas outras páginas (ou encontrar padronização melhor, talvez incluindo no Template)
Inclusive, nas outras páginas tem um MatchPoint | ... antes do título, mas pode remover isso delas, deixa só o título da página mesmo

2023-05-17 00:04 UTC, luc527 commented on src/Tecnico/Atleta/Atleta.php
> +    private ?int $id = null;
Dava pra fazer um trait TemId também [opcional]

2023-05-17 00:04 UTC, luc527 commented on src/Tecnico/Atleta/Atleta.php
> +    public function __serialize(): array
O atleta está sendo serializado em algum lugar? Senão, dá pra remover [opcional]
Fiz pro técnico (e clube) só pra guardar na sessão

2023-05-17 00:04 UTC, luc527 commented on src/Tecnico/Atleta/Atleta.php
> +        $dataNascimento = DateTime::createFromFormat('Y-m-d', $data['dataNascimento']);
Dá pra usar o Dates::parseDay

2023-05-17 00:04 UTC, luc527 commented on src/Tecnico/Atleta/Atleta.php
> +            'dataNascimento' => $this->dataNascimento->format('Y-m-d'),
Dá pra usar Dates::formatDay

2023-05-17 00:04 UTC, luc527 commented on src/Tecnico/Atleta/Sexo.php
> +    case NAO_DECLARADO = 'Não Declarado';
Acho que era melhor deixar só M e F porque o sexo é utilizado na formação de duplas
Um atleta com sexo não declarado seria inútil porque não consegue participar de nenhum tipo de dupla (MM masculina, MF mista, FF feminina)

2023-05-17 00:04 UTC, luc527 commented on src/Tecnico/Atleta/UploadImagemService.php
> +    private const MAX_FILE_SIZE = 500000;
Coloca a unidade no final do nome, tipo MAX_FILE_SIZE_BYTES (ou só B), MAX_FILE_SIZE_KB etc.

2023-05-17 00:04 UTC, luc527 commented on src/Tecnico/Atleta/UploadImagemService.php
> +    public function upload(array $file): bool
[opcional] Não vejo porque retornar um true e fazer um if ($service->upload(...)) { ... } se a função sempre que der um erro levanta uma exception
Dá no mesmo:

```php
try {
 if ($service->upload($file)) {
    a();
    b();
  }
} catch (Exception $e) {
  deuErro();
}
```

```php
try {
 $service->upload($file);
 a();
 b();
} catch (Exception $e) {
  deuErro();
}
```

2023-05-17 00:04 UTC, luc527 commented on src/Tecnico/Atleta/UploadImagemService.php
> +            throw new ValidatorException('Arquivo já existe.');
Se já existe é porque o uniqid() gerou um id já utilizado -- não deveria ser erro pro usuário
Daria pra tentar gerar um outro id até que dê certo ou pelo menos retornar um erro 500

2023-05-17 00:04 UTC, luc527 commented on src/Tecnico/Atleta/AtletaRepository.php
> +                    "Atleta '{$atleta->nomeCompleto()}' já existe",
Dá pra tirar essa validação, é possível que dois atletas tenham o mesmo nome. O técnico consegue desambiguar pela foto ou idade / data de nascimento

2023-05-17 00:04 UTC, luc527 commented on src/Tecnico/Atleta/Sexo.php
> +    case NAO_DECLARADO = 'Não Declarado';
aí tem que tirar o valor do type no banco e do <select> no cadastro

2023-05-17 00:04 UTC, luc527 commented on public/tecnico/atleta/cadastrar/index.php
> +                location.assign('/tecnico/atletas');
Não existe `/tecnico/atletas`, só `/tecnico/atleta`

2023-05-17 14:33 UTC, MateuxLucax commented on src/Tecnico/Atleta/Sexo.php
> +    case NAO_DECLARADO = 'Não Declarado';
Alterei, deixando só como M ou F e também mudei o Type do banco

2023-05-17 14:40 UTC, MateuxLucax commented on public/tecnico/atleta/cadastrar/acao.php
> +    try {
Coloquei para remover a imagem se der exception na parte de banco. Poderia ser feito também com Commit rollback mas daria mais trabalho hehe. Mas da pra repensar de outra forma isso então

2023-05-17 14:47 UTC, MateuxLucax commented on public/tecnico/atleta/cadastrar/acao.php
> +    try {
Resolvido. Fiz ser um metodo estatico a remocao de imagem. Agora no catch do repositorio ele remove a imagem

2023-05-17 14:51 UTC, MateuxLucax commented on src/Tecnico/Atleta/Atleta.php
> +    private ?int $id = null;
Criei o trait e adicionei no Tecnico e Clube tambem

2023-05-17 14:51 UTC, MateuxLucax commented on src/Tecnico/Atleta/Atleta.php
> +            'dataNascimento' => $this->dataNascimento->format('Y-m-d'),
Removi o serialize

2023-05-17 14:55 UTC, MateuxLucax commented on src/Tecnico/Atleta/UploadImagemService.php
> +    public function upload(array $file): bool
Alterei para retornar uma string (nome da imagem gerada)
<img width="544" alt="image" src="https://github.com/MateuxDotDev/badminton-manager/assets/35275029/e75146b1-8f08-4e4d-8d1e-0a91df2617b6">

2023-05-17 17:04 UTC, ghost commented
![Passed](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/QualityGateBadge/passed.svg?sanitize=true)

# Analysis Details
## 0 Issues
- ![Bug](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/bug.svg?sanitize=true) 0 Bugs
- ![Vulnerability](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/vulnerability.svg?sanitize=true) 0 Vulnerabilities
- ![Code Smell](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/code_smell.svg?sanitize=true) 0 Code Smells

## Coverage and Duplications
- ![Coverage](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/CoverageChart/100.svg?sanitize=true) 100.00% Coverage (100.00% Estimated after merge)
- ![Duplications](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/Duplications/3.svg?sanitize=true) 0.00% Duplicated Code (0.00% Estimated after merge)

**Project ID:** MateuxDotDev_badminton-manager_AYfNu-knGxuymmoUfIu7

[View in SonarQube](https://sonarqube.mateux.dev/dashboard?id=MateuxDotDev_badminton-manager_AYfNu-knGxuymmoUfIu7&pullRequest=23)

2023-05-17 18:25 UTC, ghost commented
![Passed](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/QualityGateBadge/passed.svg?sanitize=true)

# Analysis Details
## 0 Issues
- ![Bug](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/bug.svg?sanitize=true) 0 Bugs
- ![Vulnerability](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/vulnerability.svg?sanitize=true) 0 Vulnerabilities
- ![Code Smell](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/code_smell.svg?sanitize=true) 0 Code Smells

## Coverage and Duplications
- ![Coverage](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/CoverageChart/100.svg?sanitize=true) 100.00% Coverage (100.00% Estimated after merge)
- ![Duplications](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/Duplications/3.svg?sanitize=true) 0.00% Duplicated Code (0.00% Estimated after merge)

**Project ID:** MateuxDotDev_badminton-manager_AYfNu-knGxuymmoUfIu7

[View in SonarQube](https://sonarqube.mateux.dev/dashboard?id=MateuxDotDev_badminton-manager_AYfNu-knGxuymmoUfIu7&pullRequest=23)

2023-05-17 23:49 UTC, luc527 approved these changes

2023-05-17 23:49 UTC, luc527 commented on src/Util/Services/UploadImagemService/UploadImagemService.php
> +                'Formato de arquivo inválido. Permitidos' . implode(', ', self::ALLOWED_EXTENSIONS)
```php
'... Permitidos: ' . implode(...)
```
Senão vai ficar "Formato de arquivo inválido. Permitidosjpg, jpeg, png, gif"

2023-05-17 23:56 UTC, merged