Permitir técnico se cadastrar com um clube existente
MateuxDotDev/badminton-manager pull request #26
Opened 2023-05-20 19:07 UTC by luc527

2023-05-21 18:58 UTC, MateuxLucax requested changes

2023-05-21 18:58 UTC, MateuxLucax commented on public/assets/js/debounce-throttle.js
> +function debounce(t, f) {
na branch que estou mexendo (https://github.com/MateuxDotDev/badminton-manager/pull/27) também utiliza esses esquemas. Porém também criei um arquivo de utilitários extras (para filtragem), no arquivo `public/assets/js/utils.js`.

Será que não seria bom criar um arquivo que contenha mais desses utilitários? Ou ir criando arquivos conforme a necessidade. Tipo ao invés do `utils.js` lá naquela branch teria um `search.js` ou algo assim?

2023-05-21 18:58 UTC, MateuxLucax commented on public/cadastro/acao.php
> +            fn($termo) => "nome like '%" . addslashes($termo) . "%'",
Talvez fazer alguma limpeza para evitar SQLInjection nessa parte? Me parece manipulação de string bruta apenas

2023-05-21 18:58 UTC, MateuxLucax commented on public/cadastro/index.php
> +            <div class="mb-3">
Ele é case-sensitive nas buscas. Não seria bom se não fosse? (dependendo do esforço que desse, n importa muito também).

2023-05-21 18:58 UTC, MateuxLucax commented on public/cadastro/index.php
> +                <input type="text" class="form-control" name="clube" autocomplete="off"/>
https://getbootstrap.com/docs/5.2/forms/form-control/#datalists

Será que um datalist não seria melhor? Esse do radio me parece muito complicado.
Aí só fazer um controle para buscar clube conforme o que o cara escreveu. Se existir um com mesmo nome (case-insensitive), utilizar ele como clube.

2023-05-21 18:58 UTC, MateuxLucax commented on src/Tecnico/TecnicoRepository.php
> +        $sql  = "SELECT id FROM clube WHERE nome = :nome";
<img width="508" alt="image" src="https://github.com/MateuxDotDev/badminton-manager/assets/35275029/dc3d14b3-377b-417e-ac5f-0cf2056dfc42">

Adicionar uma forma de não ser case-sensitive

2023-05-23 01:08 UTC, luc527 commented on public/assets/js/debounce-throttle.js
> +function debounce(t, f) {
Feito, criei um `utils.js` e movi as funções para lá. Pode ficar tudo num arquivo `utils.js` mesmo.

2023-05-23 01:09 UTC, luc527 commented on public/cadastro/acao.php
> +            fn($termo) => "nome like '%" . addslashes($termo) . "%'",
Feito, troquei por query preparada (`nome ILIKE ?`)

2023-05-23 01:10 UTC, luc527 commented on public/cadastro/index.php
> +            <div class="mb-3">
Corrigido com um `ILIKE` no lugar de `LIKE`

2023-05-23 01:11 UTC, luc527 commented on public/cadastro/index.php
> +                <input type="text" class="form-control" name="clube" autocomplete="off"/>
É uma boa, e de fato isso que eu fiz com os radios ficou mais complicado do que eu gostaria. Se eu soubesse do datalist teria tentando fazer com ele. Mas acho melhor colocar essa refatoração como uma tarefa pra focar nas tarefas mais importantes agora, aí alguém faz depois se quiser. (Na prática provavelmente vai ficar assim mesmo)

2023-05-23 01:14 UTC, luc527 commented on src/Tecnico/TecnicoRepository.php
> +        $sql  = "SELECT id FROM clube WHERE nome = :nome";
Feito, troquei por um `ILIKE`

2023-05-23 01:18 UTC, luc527 commented on public/cadastro/acao.php
> +        LEFT JOIN tecnico t
Corrigi também um erro onde clubes sem atletas não eram mostrados (por causa do JOIN, corrigido com LEFT JOIN)

2023-05-23 12:43 UTC, MateuxLucax approved these changes

2023-05-23 12:57 UTC, merged