feat: adicionada listagem de atletas
MateuxDotDev/badminton-manager pull request #27
Opened 2023-05-21 01:37 UTC by MateuxLucax

2023-05-24 00:40 UTC, luc527 requested changes

2023-05-24 00:40 UTC, luc527 commented on public/tecnico/atletas/index.php
> +            conteudo.insertAdjacentHTML('beforeend', createAtletaCard(atleta));
Em vez de criar o card de atleta preenchendo uma string de template, poderia ser feita com uma tag `<template>`. Provavelmente é mais eficiente, porque o HTML é parseado uma vez só, e não precisa alocar uma string grandona pra cada card (considerando ainda que vão sendo criadas strings intermediárias preenchendo cada {{}} do template). Tipo assim:

```html
<template id="template-atleta">
  <div>
    <bold>Nome do atleta</bold>
    <span class="atleta-nome"></span>
  </div>
</template>
```

aí no js
```js
const templateAtleta = document.querySelector('#template-atleta');

/**
 * @return {HTMLElement} (não string)
 */
function criarAtletaCard(atleta) {
  const elemento = templateAtleta.content.cloneNode(true).firstElementChild; // o firstElementChild não sei se sempre precisa
  elemento.querySelector('.atleta-nome').innerText = atleta.nome;
  return elemento;
}
```

2023-05-24 00:40 UTC, luc527 commented on public/tecnico/atletas/index.php
> +            conteudo.insertAdjacentHTML('beforeend', createAtletaCard(atleta));
Vi agora porque o .firstElementChild: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template#avoiding_documentfragment_pitfall
Mas poderia ser .firstElementChild.cloneNode(true) em vez de .cloneNode(true).firstElementChild

2023-05-24 00:40 UTC, luc527 commented on public/tecnico/atletas/atleta-card.html
> +<div class="atleta-card card card-body" id="atleta-{{ id }}">
Fica ruim no mobile esse layout

![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/a9563359-5529-4f9c-86ff-9f2d4ef44ebe)

2023-05-24 00:40 UTC, luc527 commented on public/tecnico/atletas/atleta-card.html
> +                <small class="max-3-lines">{{ informacoes_adicionais }}</small>
Quando não tem informações adicionais poderia mostrar "Sem informações adicionais". Mas não um label "Informações adicionais" com valor "Sem informações adicionais", só o "Sem informações adicionais" mesmo.
![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/c7d45be2-57ed-4be6-93a3-805649eb1b3b)

2023-05-24 00:40 UTC, luc527 commented on public/tecnico/atletas/atleta-card.html
> +                <h6 class="mb-0">{{ idade }} anos</h6>
Não deveria permitir criar atleta com data de nascimento no futuro
![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/081a5b3b-05d9-4cb6-9342-e226466f1d25)

2023-05-24 00:40 UTC, luc527 commented on public/tecnico/atletas/index.php
> +    <?php if ($hasError): ?>
O $hasError só é setado como true abaixo daqui, então é sempre false

2023-05-24 00:40 UTC, luc527 commented on public/tecnico/atletas/index.php
> +    inputPesquisa.addEventListener('keydown', () => {
Dá pra substituir por uma chamada à função `debounce`

2023-05-24 00:40 UTC, luc527 commented on public/tecnico/atletas/index.php
> +    const chavesPesquisa = ['nomeCompleto', 'idade', 'dataNascimento', 'sexo', 'informacoesAdicionais'];
O filtro por idade não parece estar funcionando
![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/b80b465f-72d0-431f-b61e-19e1832bb778)

![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/ca39bb48-a44d-4055-8fa6-335c12900ecf)

Inclusive, quando nenhum atleta aparece, poderia mostrar um alerta de "nenhum atleta encontrado"

2023-05-24 00:40 UTC, luc527 commented on public/tecnico/atletas/index.php
> +    const chavesPesquisa = ['nomeCompleto', 'idade', 'dataNascimento', 'sexo', 'informacoesAdicionais'];
Acho que o filtro não funciona porque o typeof da idade é number, não string
Quando é um número ele pode converter pra string e testar
Atualmente só compara quando o tipo é string

2023-05-25 22:52 UTC, MateuxLucax commented on public/tecnico/atletas/index.php
> +            conteudo.insertAdjacentHTML('beforeend', createAtletaCard(atleta));
Mas e quando tiver um dado que fique dentro de um elemento, por exemplo:

```html
<img class="img-fluid rounded-circle profile-pic" src="/assets/images/profile/{{ imagem_perfil }}" alt="Foto de perfil de {{ nome_completo }}">
```

Dessa forma me parece um pouco mais complexa. Processar string assim parece mais simples. Mas vou dar uma analisada nessa forma com `<template></template>`.

2023-05-25 22:54 UTC, MateuxLucax commented on public/tecnico/atletas/index.php
> +    inputPesquisa.addEventListener('keydown', () => {
Sim, é que quando criei ainda não tinha sido feito o merge com aquelas funções. Vou alterar aqui.

2023-05-25 22:54 UTC, MateuxLucax commented on public/tecnico/atletas/index.php
> +    <?php if ($hasError): ?>
Corrigido

2023-05-25 23:10 UTC, MateuxLucax commented on public/tecnico/atletas/index.php
> +    const chavesPesquisa = ['nomeCompleto', 'idade', 'dataNascimento', 'sexo', 'informacoesAdicionais'];
Resolvido, agora pode testar números também.

2023-05-25 23:18 UTC, MateuxLucax commented on public/tecnico/atletas/atleta-card.html
> +                <small class="max-3-lines">{{ informacoes_adicionais }}</small>
Resolvido.

2023-05-25 23:28 UTC, MateuxLucax commented on public/tecnico/atletas/atleta-card.html
> +<div class="atleta-card card card-body" id="atleta-{{ id }}">
Resolvido. O problema era que o `max-width` estava sendo aplicado em um elemento errado. Deveria estar no elemento pai dele.

2023-05-25 23:45 UTC, MateuxLucax commented on public/tecnico/atletas/index.php
> +            conteudo.insertAdjacentHTML('beforeend', createAtletaCard(atleta));
Alterado. Agora fica como template.

2023-05-26 01:30 UTC, luc527 commented on public/tecnico/atletas/index.php
> +            conteudo.insertAdjacentHTML('beforeend', createAtletaCard(atleta));
Não vi ainda como ficou o código, mas nesse caso dá pra fazer
```js
const divAtleta = templateAtleta.content.firstElementChild.cloneNode(true);
divAtleta.setAttribute('alt', replaceKeyInString(divAtleta.getAttribute('alt'), 'nome_completo', nomeCompleto);
```
talvez com um método auxiliar `replaceInAttribute(elemento, atributo, chave, valor)`
ou ainda nem colocar o "Foto de perfil de {{ nome_completo }}" dentro do elemento, fazer por fora:
```js
const divAtleta = templateAtleta.content.firstElementChild.cloneNode(true);
divAtleta.setAttribute('alt', `Foto de perfil de ${nomeCompleto}`);
```

2023-05-26 01:35 UTC, MateuxLucax commented on public/tecnico/atletas/index.php
> +            conteudo.insertAdjacentHTML('beforeend', createAtletaCard(atleta));
Consegui resolver facil tbm, ficou assim:

```js
const botaoInfo = card.querySelector('.botao-info');
botaoInfo.setAttribute('data-bs-content', `Criado em: ${atleta.dataCriacao}.\nAlterado em: ${atleta.dataAlteracao}.`);

const img = card.querySelector('.profile-pic');
img.src = `/assets/images/profile/${atleta.foto}`;
img.alt = `Foto de perfil de ${atleta.nomeCompleto}`;
```

2023-05-26 01:43 UTC, MateuxLucax commented on public/tecnico/atletas/index.php
> +            conteudo.insertAdjacentHTML('beforeend', createAtletaCard(atleta));
Criei o metodo utilitario:

```js
// public/assets/js/utils.js

/**
 * Set the value of an attribute of an element
 *
 * @param {HTMLElement} element - The element to be modified
 * @param {string} attribute    - The attribute to be modified
 * @param {string} value        - The value to be set
 */
const setInAttribute = (element, attribute, value) => {
    element.setAttribute(attribute, value);
}

// public/tecnico/atletas/index.php

const botaoInfo = card.querySelector('.botao-info');
const img = card.querySelector('.profile-pic');

setInAttribute(botaoInfo, 'data-bs-content', `Criado em: ${atleta.dataCriacao}.\nAlterado em: ${atleta.dataAlteracao}.`);
setInAttribute(img, 'src', `/assets/images/profile/${atleta.foto}`);
setInAttribute(img, 'alt', `Foto de perfil de ${atleta.nomeCompleto}`);
```

2023-05-26 01:54 UTC, luc527 requested changes

2023-05-26 01:54 UTC, luc527 commented on public/tecnico/atletas/cadastrar/acao.php
> +        throw new ValidatorException('Data de nascimento não pode ser maior ou igual que a data atual');
O alerta fica na tela por pouco tempo e fica ruim de ler, sugiro resumir pra "Data de nascimento não pode estar no futuro" ou algo assim

![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/424efdd0-0c13-4cfb-8027-cdab56e6df45)

2023-05-26 01:54 UTC, luc527 commented on public/assets/js/utils.js
> +const setInAttribute = (element, attribute, value) => {
Essa função não faz muita coisa, é só chamar o setAttribute direto.
```js
element.setAttribute(attribute, value)
```
é até mais curto que
```js
setInAttribute(element, attribute, value)
```

2023-05-26 01:54 UTC, luc527 commented on src/Util/Template/common/tecnicoNav.html
>            </a>
Aproveita e troca pra "Meus atletas"

2023-05-26 01:56 UTC, MateuxLucax commented on src/Util/Template/common/tecnicoNav.html
>            </a>
Alterado

2023-05-26 01:57 UTC, MateuxLucax commented on public/assets/js/utils.js
> +const setInAttribute = (element, attribute, value) => {
Removi o metodo la, e atualizei para:

```js
const botaoInfo = card.querySelector('.botao-info');
const img = card.querySelector('.profile-pic');

botaoInfo.setAttribute('data-bs-content', `Criado em: ${atleta.dataCriacao}.\nAlterado em: ${atleta.dataAlteracao}.`);  
img.setAttribute('src', `/assets/images/profile/${atleta.foto}`);
img.setAttribute('alt', `Foto de perfil de ${atleta.nomeCompleto}`);
```

2023-05-26 02:00 UTC, MateuxLucax commented on public/tecnico/atletas/cadastrar/acao.php
> +        throw new ValidatorException('Data de nascimento não pode ser maior ou igual que a data atual');
Aumentei o tempo para 5s e troquei a mensagem.

2023-05-26 02:04 UTC, luc527 approved these changes

2023-05-26 02:04 UTC, merged