Consulta de atletas vem com filtros preenchidos para mostrar atletas compatíveis com o atleta passado por GET
MateuxDotDev/badminton-manager pull request #30
Opened 2023-06-04 01:09 UTC by luc527

2023-06-09 02:22 UTC, MateuxLucax requested changes

2023-06-09 02:22 UTC, MateuxLucax commented on src/Tecnico/Atleta/AtletaRepository.php
> +    // TODO na verdade isso aqui deveria estar no AtletaCompeticaoRepository
Aguardando o merge da outra branch para poder aprovar

2023-06-10 14:41 UTC, luc527 commented on src/Tecnico/Atleta/AtletaRepository.php
> +    // TODO na verdade isso aqui deveria estar no AtletaCompeticaoRepository
Feito o merge, método movido ao AtletaCompeticaoRepository

2023-06-11 00:36 UTC, MateuxLucax approved these changes

2023-06-11 00:36 UTC, merged