feat: adicionado email de confirmacao de inclusao competciao (missing…
MateuxDotDev/badminton-manager pull request #31
Opened 2023-06-09 01:34 UTC by MateuxLucax

… envio apos inclusao)

2023-06-11 15:58 UTC, luc527 requested changes

2023-06-11 15:58 UTC, luc527 commented on public/tecnico/atletas/acao.php
> +    atletasController($session, $token)->enviar();
Variável `$token` não existe, devia ser `$reqToken` imagino

2023-06-11 15:58 UTC, luc527 commented on public/tecnico/atletas/acao.php
> +use stdClass;
Remover, causa um warning
![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/3e376b00-0b55-44ee-9ba4-3503dfa5ac14)

2023-06-11 15:58 UTC, luc527 commented on public/tecnico/atletas/acao.php
> +        $acao = $req['acao'] ?? 'Ação não informada';
Trocar por um `if (!array_key_exists('acao', $req)) return Response::erro('Ação não informada')` ou algo equivalente. Caso não tenha ação, o retorno fica "Ação 'Ação não informada' inválida", que fica estranho de ler.

2023-06-11 15:58 UTC, luc527 commented on public/tecnico/atletas/acao.php
> +        $req = Request::getJson();
O `getJson` não funciona porque a request pra alterar o atleta vem no `$_POST`

2023-06-11 15:58 UTC, luc527 commented on public/tecnico/atletas/cadastrar/acao.php
> +if ($session->getTecnico() === null) {
Pode ser só `if (!$session->isTecnico())`

2023-06-11 15:58 UTC, luc527 commented on public/tecnico/atletas/cadastrar/index.php
> +if ($session->getTecnico() === null) {
Pode ser só `if (!$session->isTecnico())`

2023-06-11 15:58 UTC, luc527 commented on public/tecnico/atletas/acao.php
> +    if ($session->getTecnico() === null && $reqToken === null) {
Pode ser só `if (!$session->isTecnico() && $reqToken === null)`

2023-06-11 15:58 UTC, luc527 commented on public/tecnico/atletas/acao.php
> +    if ($session->getTecnico() === null && $reqToken === null) {
O mesmo logo abaixo, pode ser `ìf ($session->isTecnico())`

2023-06-11 15:58 UTC, luc527 commented on public/tecnico/atletas/acao.php
> +        $idTecnico = $session->getTecnico()->id();
Essa variável `$idTecnico` não é utilizada
Me parece que esse `if` é desnecessário, podia ser só `if (!$session->isTecnico())` e dentro o conteúdo do `else`.

2023-06-11 15:58 UTC, luc527 commented on public/test/test_mail.php
> +            'acao' => 'alterar',
Os nomes de ação não teriam que ser mais específicos? Tipo `alterarAtleta` e `removerAtleta`. Esse mesmo campo `acao` vai ser utilizado para outras ações de alteração e remoção.

2023-06-11 15:58 UTC, luc527 commented on public/test/test_mail.php
> +                'nome' => 'Mateus Lucas',
Por que o nome é enviado junto? Não encontrei nenhum lugar onde o nome no token é utilizado.

2023-06-14 16:07 UTC, MateuxLucax commented on public/test/test_mail.php
> +                'nome' => 'Mateus Lucas',
Foi o Github Copilot que colocou. Ali eh so mock pra testar mesmo

2023-06-15 01:26 UTC, ghost commented
![Passed](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/QualityGateBadge/passed.svg?sanitize=true)

# Analysis Details
## 0 Issues
- ![Bug](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/bug.svg?sanitize=true) 0 Bugs
- ![Vulnerability](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/vulnerability.svg?sanitize=true) 0 Vulnerabilities
- ![Code Smell](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/code_smell.svg?sanitize=true) 0 Code Smells

## Coverage and Duplications
- ![Coverage](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/CoverageChart/100.svg?sanitize=true) 100.00% Coverage (100.00% Estimated after merge)
- ![Duplications](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/Duplications/3.svg?sanitize=true) 0.00% Duplicated Code (0.00% Estimated after merge)

**Project ID:** MateuxDotDev_badminton-manager_AYfNu-knGxuymmoUfIu7

[View in SonarQube](https://sonarqube.mateux.dev/dashboard?id=MateuxDotDev_badminton-manager_AYfNu-knGxuymmoUfIu7&pullRequest=31)

2023-06-16 00:15 UTC, luc527 approved these changes

2023-06-16 00:16 UTC, merged