feat: adicionado email ao incluir atleta
MateuxDotDev/badminton-manager pull request #36
Opened 2023-06-16 01:04 UTC by MateuxLucax

2023-06-16 22:17 UTC, luc527 requested changes
No tecnico/atletas/index.php, linha 31, tem que dar unserialize no técnico
![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/b54a1a92-7aa3-47f0-aa91-a765fa77de5e)

Tem que excluir o(s) registro(s) na atleta_competicao (e atleta_competicao_categoria e atleta_competicao_dupla) também
![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/ae2eb83e-4b53-40c1-b800-298c80e77faa)

2023-06-17 20:25 UTC, MateuxLucax commented
@luc527 so falta a parte de filtrar atletas nao compativais. Mas tambem nao eh o foco dessa task. Porem vou debbugar para ver se descubro algo.

2023-06-17 20:56 UTC, MateuxLucax commented
@luc527 Corrigi. Estava tudo funcionando porém só não filtrava ao carregar a página. Adicionei isso agora. Se concordar, podemos manter assim e mergear.

2023-06-19 02:18 UTC, luc527 commented
Foi feito o `json_decode` mas faltou o `unserialize`, e também tem que corrigir de `['id']` pra `->id()`:
![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/3fd5512b-35fb-43da-8aef-d638bd5c3117)
Aí trocar de `$tecnicoJson` pra `$tecnico` também

Esse erro não foi corrigido:
Ao excluir um atleta (tabela atleta), tem que excluir o(s) registro(s) na atleta_competicao (e atleta_competicao_categoria e atleta_competicao_dupla) também
![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/cea7b0b4-c027-467b-b66b-b5299a48bb35)

Quando acesso o sistema sem estar logado, ocorre esse erro na página de consulta de atletas da competição:
![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/bceb52b0-dad1-4a8d-b7ca-bc83927b2a54)

Talvez só aconteça ao entrar no sistema com o token

2023-06-20 00:14 UTC, luc527 requested changes
Foi feito o json_decode mas faltou o unserialize, e também tem que corrigir de ['id'] pra ->id():
Aí trocar de $tecnicoJson pra $tecnico também

Esse erro não foi corrigido:
Ao excluir um atleta (tabela atleta), tem que excluir o(s) registro(s) na atleta_competicao (e atleta_competicao_categoria e atleta_competicao_dupla) também
(mesma imagem do último comentário)

Quando acesso o sistema sem estar logado, ocorre um erro na página de consulta de atletas da competição (não aparece nenhum resultado, nem o alerta de "nenhum atleta" -- acho que era isso)

Talvez só aconteça ao entrar no sistema com o token

(eu tinha prints mas acabei copiando do comentário para a revisão e perdi)

2023-06-22 23:55 UTC, luc527 approved these changes
Ficou meio estranha a parte de remover atleta, porque o e-mail é enviado só quando o atleta é incluído numa competição, mas não dá pra remover o atleta se ele estiver numa competição, então a ação de excluir nunca vai funcionar. Por questão de tempo vou aprovar, mas se você tiver um tempo acho que fica melhor tirar fora o botão de remover do e-mail.

A regra de negócio pra implementar corretamente essa funcionalidade de remover teria que considerar as solicitações pendentes envolvendo o atleta, as duplas que já foram formadas etc., e não temos tempo pra isso agora. Talvez daria pra só fazer um CASCADE, já que o propósito do sistema não é manter um registro a longo prazo dessas informações, mas somente ajudar na hora de encontrar uma dupla de outro clube. Quando a competição terminar não sei se tem mais muito valor manter essas informações.

2023-06-23 12:15 UTC, luc527 requested changes

2023-06-23 12:15 UTC, luc527 commented on src/Tecnico/Atleta/AtletaRepository.php
> +            DELETE FROM solicitacao_dupla_concluida
A solicitacao_dupla_pendente não pode ser deletada porque podem ter outras solicitações que referenciam essa pela solicitao_cancelamento_id. Sugiro só tirar essa coluna mesmo, na prática não vamos usar pra nada.

2023-06-23 12:15 UTC, luc527 commented on src/Tecnico/Atleta/AtletaRepository.php
> +            DELETE FROM dupla
A dupla tem que ser deletada antes, porque tem uma coluna solicitacao_id que referencia a solicitacao_dupla_concluida que originou ela.

2023-06-23 16:31 UTC, ghost commented
![Passed](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/QualityGateBadge/passed.svg?sanitize=true)

# Analysis Details
## 0 Issues
- ![Bug](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/bug.svg?sanitize=true) 0 Bugs
- ![Vulnerability](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/vulnerability.svg?sanitize=true) 0 Vulnerabilities
- ![Code Smell](https://sonarqube.mateux.dev/static/communityBranchPlugin/common/code_smell.svg?sanitize=true) 0 Code Smells

## Coverage and Duplications
- ![Coverage](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/CoverageChart/100.svg?sanitize=true) 100.00% Coverage (100.00% Estimated after merge)
- ![Duplications](https://sonarqube.mateux.dev/static/communityBranchPlugin/checks/Duplications/3.svg?sanitize=true) 0.00% Duplicated Code (0.00% Estimated after merge)

**Project ID:** MateuxDotDev_badminton-manager_AYfNu-knGxuymmoUfIu7

[View in SonarQube](https://sonarqube.mateux.dev/dashboard?id=MateuxDotDev_badminton-manager_AYfNu-knGxuymmoUfIu7&pullRequest=36)

2023-06-23 22:03 UTC, luc527 approved these changes

2023-06-23 22:03 UTC, merged