feat: adicionado envio de email ao enviar solicitacao via cron
MateuxDotDev/badminton-manager pull request #38
Opened 2023-06-19 01:21 UTC by MateuxLucax

2023-06-20 01:32 UTC, luc527 requested changes
No e-mail, trocar "convite" pra "solicitação":

![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/b63f9be9-35da-4f62-8ad9-068c5469590e)

Além disso, o e-mail poderia incluir as informações adicionais do atleta, do atleta na competição e do técnico. Também a foto.


O e-mail mostra só o atleta remetente, não o destinatário (e os dados dele).
**Acho que tem que repensar todo o layout desse e-mail.**


Além disso, não entendi campo "modalidade".

2023-06-20 01:32 UTC, luc527 commented on src/Util/Traits/TemUuid.php
> +    private ?String $uuid = null;
mudar pra `?string`

2023-06-20 01:32 UTC, luc527 commented on public/tecnico/competicoes/atletas/controller.php
> +        $notificacoes = $notificacoesRepo->getViaId1($id);
Tinha que incluir o tipo da notificação no filtro também

2023-06-20 01:32 UTC, luc527 commented on src/Mail/MailRepository.php
> +        $sql = <<<SQL
A ideia do envio_email_notificacao era fazer o INSERT só quando o e-mail é efetivamente enviado pelo cron, e buscar os e-mails pendentes por um WHERE NOT EXISTS (SELECT .. FROM envio_email_notificacao) ou algo do tipo. Atualmente ele cria esse registro e busca os e-mails pendentes por um JOIN envio_email_notificacao WHERE enviado_em IS NULL. O problema é que o enviado_em é NOW() por padrão, então isso não funciona. Dá pra corrigir removendo o NOW() de padrão ou movendo esse INSERT para a hora em que o envio realmente é enviado.

2023-06-20 01:32 UTC, luc527 commented on src/Mail/MailRepository.php
> +        $sql = <<<SQL
Vi que foi feito o drop da not null, mas teria ainda que deixar o default null numa outra migration.

2023-06-20 01:32 UTC, luc527 commented on public/tecnico/competicoes/atletas/controller.php
> +                $notificacaoIdRem = $notificacao->id();
O método retorna um array de arrays, mas aqui a notificação é acessada com `->id()` quando deveria ser `['id']`


![image](https://github.com/MateuxDotDev/badminton-manager/assets/48414967/cfced12e-c04d-434c-aabd-a61986d9a0c9)

2023-06-20 02:45 UTC, MateuxLucax commented on src/Mail/MailRepository.php
> +        $sql = <<<SQL
adicionei na migration pra tirar o `DEFAULT NOW()`

2023-06-23 00:28 UTC, luc527 approved these changes

2023-06-23 00:29 UTC, merged